# Generated by Django 5.1.6 on 2025-02-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=250, verbose_name='Название товара')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розничная цена')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
