# Generated by Django 5.1.6 on 2025-02-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия клиента')),
                ('language', models.CharField(max_length=3, verbose_name='Язык клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес клиента')),
                ('car', models.CharField(blank=True, max_length=255, null=True, verbose_name='Машина клиента')),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
